image:
  file: .gitpod.Dockerfile
tasks:
  - name: setup
    before: |-
      # REMOVE USER VALIDATION -Y ON JAVA 17 INSTALLATION
      sed -i '1,$s/sdkman_auto_answer=false/sdkman_auto_answer=true/' /home/gitpod/.sdkman/etc/config
      sed -i '1,$s/sdkman_selfupdate_enable=true/sdkman_selfupdate_enable=false/' /home/gitpod/.sdkman/etc/config

      # JAVA 17 INSTALL
      sdk install java

      # get Astra CLI
      mkdir bin
      curl -Ls "https://dtsx.io/get-astra-cli" | bash

    command: |-
      # Open README in VS Code (or default IDE)
      gp open README.md

ports:
  - port: 8080
    onOpen: open-browser
    visibility: private
